import PDFDocument from 'pdfkit'
import { Invoice } from '../models/Invoice.js'
import { User } from '../models/User.js'

const GREEN = '#235e42'
const COPPER = '#b87348'
const INK = '#243430'
const SOFT = '#5c6f68'

const money = (n, currency = 'USD') =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 2 }).format(n)
const dateStr = (d) =>
  new Date(d).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })

/** GET /api/invoices/:id/pdf — a clean, branded, printable invoice. */
export async function invoicePdfHandler(req, res) {
  const invoice = await Invoice.findOne({ _id: req.params.id, userId: req.userId }).populate(
    'clientId',
    'name email contactName'
  )
  if (!invoice) return res.status(404).json({ error: 'Invoice not found' })
  const user = await User.findById(req.userId)
  renderInvoicePdf(invoice, user, res)
}

/** Shared renderer — also used by the public (tokenized) invoice page. */
export function renderInvoicePdf(invoice, user, res) {
  const inv = invoice.toObject({ virtuals: true })

  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader('Content-Disposition', `inline; filename="${inv.number}.pdf"`)

  const doc = new PDFDocument({ size: 'LETTER', margin: 54 })
  doc.pipe(res)
  const right = doc.page.width - 54

  // header
  doc.fillColor(GREEN).font('Helvetica-Bold').fontSize(22).text(user?.businessName || user?.name || 'Invoice', 54, 54)
  doc.fillColor(COPPER).font('Helvetica-Bold').fontSize(13).text('INVOICE', 54, 60, { align: 'right', width: right - 54 })
  doc.moveTo(54, 92).lineTo(right, 92).lineWidth(2).strokeColor(GREEN).stroke()

  // meta block
  doc.fillColor(SOFT).font('Helvetica').fontSize(9.5)
  doc.text(`Invoice number: ${inv.number}`, 54, 104, { align: 'right', width: right - 54 })
  doc.text(`Issued: ${dateStr(inv.issueDate)}`, { align: 'right', width: right - 54 })
  doc.text(`Due: ${dateStr(inv.dueDate)}`, { align: 'right', width: right - 54 })

  doc.fillColor(SOFT).text('Billed to', 54, 104)
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(11.5).text(inv.clientId?.name || '—', 54, 118)
  doc.font('Helvetica').fontSize(9.5).fillColor(SOFT)
  if (inv.clientId?.contactName) doc.text(inv.clientId.contactName, 54)
  if (inv.clientId?.email) doc.text(inv.clientId.email, 54)

  // line items table
  let y = 190
  const cols = { desc: 54, qty: right - 220, unit: right - 150, amt: right - 70 }
  doc.rect(54, y - 6, right - 54, 22).fill(GREEN)
  doc.fillColor('white').font('Helvetica-Bold').fontSize(9)
  doc.text('DESCRIPTION', cols.desc + 8, y)
  doc.text('QTY', cols.qty, y, { width: 50, align: 'right' })
  doc.text('UNIT PRICE', cols.unit, y, { width: 60, align: 'right' })
  doc.text('AMOUNT', cols.amt, y, { width: 60, align: 'right' })
  y += 26

  const items = inv.lineItems?.length
    ? inv.lineItems
    : [{ description: inv.notes || 'Professional services', quantity: 1, unitPrice: inv.amount }]
  doc.font('Helvetica').fontSize(10)
  for (const li of items) {
    doc.fillColor(INK).text(li.description, cols.desc + 8, y, { width: cols.qty - cols.desc - 24 })
    const rowH = Math.max(doc.heightOfString(li.description, { width: cols.qty - cols.desc - 24 }), 12)
    doc.fillColor(SOFT)
    doc.text(String(li.quantity), cols.qty, y, { width: 50, align: 'right' })
    doc.text(money(li.unitPrice, inv.currency), cols.unit, y, { width: 60, align: 'right' })
    doc.fillColor(INK).text(money(li.quantity * li.unitPrice, inv.currency), cols.amt, y, { width: 60, align: 'right' })
    y += rowH + 10
    doc.moveTo(54, y - 5).lineTo(right, y - 5).lineWidth(0.5).strokeColor('#e7e0d4').stroke()
  }

  // totals
  y += 8
  const totalLine = (label, value, bold = false, color = INK) => {
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(bold ? 12 : 10).fillColor(color)
    doc.text(label, cols.unit - 60, y, { width: 120, align: 'right' })
    doc.text(value, cols.amt, y, { width: 60, align: 'right' })
    y += bold ? 20 : 16
  }
  totalLine('Total', money(inv.amount, inv.currency), true, GREEN)
  if (inv.amountPaid > 0) {
    totalLine('Paid', `–${money(inv.amountPaid, inv.currency)}`)
    totalLine('Balance due', money(inv.balance, inv.currency), true, COPPER)
  }

  if (inv.notes) {
    y += 14
    doc.font('Helvetica').fontSize(9.5).fillColor(SOFT).text(`Notes: ${inv.notes}`, 54, y, { width: right - 108 })
  }

  doc.fontSize(8.5).fillColor(SOFT).text('Generated by Penny — your AI back office', 54, doc.page.height - 80, {
    align: 'center',
    width: right - 54,
    lineBreak: false,
  })
  doc.end()
}
